# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5YnhHXOucn2x4z2nSwqeWxy7mZPBQUz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Create fake data (simulating 10 days of pump data, every 10 minutes)
np.random.seed(42)
time = pd.date_range(start='2026-01-01', periods=1440, freq='10T')
flow = np.random.normal(100, 5, 1440)  # Flow around 100 m3/h
pressure = 50 + (flow * 0.5) + np.random.normal(0, 2, 1440) # Pressure depends on flow

# Inject a FAULT (performance drop) in the middle for 200 readings
pressure[600:800] = pressure[600:800] - 15  # Sudden pressure drop!

data = pd.DataFrame({'Timestamp': time, 'Flow_m3h': flow, 'Pressure_bar': pressure})
data.to_csv('pump_data.csv', index=False)
print("Fake data created successfully!")

# Load the data
df = pd.read_csv('pump_data.csv')

# Simple anomaly detection (Z-score)
mean_p = df['Pressure_bar'].mean()
std_p = df['Pressure_bar'].std()
df['Anomaly'] = abs(df['Pressure_bar'] - mean_p) > (2.5 * std_p)

# Create the exact dashboard OneSubsea would love
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8))

# Plot 1: Time series (Pressure drop highlighted in red)
ax1.plot(df['Timestamp'], df['Pressure_bar'], 'b-', linewidth=0.8, label='Normal')
ax1.scatter(df[df['Anomaly']]['Timestamp'], df[df['Anomaly']]['Pressure_bar'],
            color='red', s=15, label='Performance Deviation')
ax1.set_ylabel('Pressure (bar)')
ax1.set_title('Subsea Pump - Real-Time Pressure Monitoring')
ax1.legend()

# Plot 2: Flow vs Pressure (showing the fault zone)
ax2.scatter(df[~df['Anomaly']]['Flow_m3h'], df[~df['Anomaly']]['Pressure_bar'],
            color='blue', alpha=0.3, label='Normal Operation')
ax2.scatter(df[df['Anomaly']]['Flow_m3h'], df[df['Anomaly']]['Pressure_bar'],
            color='red', s=30, label='Fault Condition')
ax2.set_xlabel('Flow (m3/h)')
ax2.set_ylabel('Pressure (bar)')
ax2.set_title('Flow vs. Pressure Curve (Anomaly Detection)')
ax2.legend()

plt.tight_layout()
plt.savefig('pump_dashboard.png', dpi=150)  # Saves the image
plt.show()
print("Dashboard created! Look for the image above.")

from google.colab import drive
drive.mount('/content/drive')